spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3307/springbootdemo?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  type-aliases-package: com.shiro.bean
  mapper-locations: classpath:mapper/*.xml